-- NRT ONLINE BILTY / LR DATABASE
create table if not exists public.lrs (
  id bigint generated by default as identity primary key,
  lr_no text not null unique,
  lr_date date not null default current_date,
  vehicle_no text,
  from_location text,
  to_location text,
  delivery_type text,
  consignor_name text,
  consignor_phone text,
  consignee_name text,
  consignee_phone text,
  packages integer default 0,
  weight numeric default 0,
  goods text,
  freight numeric default 0,
  other_charges numeric default 0,
  remarks text,
  status text not null default 'Booked',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.lrs enable row level security;

-- Authenticated NRT users can manage LR records.
create policy "NRT authenticated select" on public.lrs
for select to authenticated using (true);

create policy "NRT authenticated insert" on public.lrs
for insert to authenticated with check (true);

create policy "NRT authenticated update" on public.lrs
for update to authenticated using (true) with check (true);

create policy "NRT authenticated delete" on public.lrs
for delete to authenticated using (true);

create index if not exists lrs_lr_no_idx on public.lrs(lr_no);
create index if not exists lrs_lr_date_idx on public.lrs(lr_date);
